/*
 * School Management System API
 * APIs for managing branches, employees, students, receipts, etc.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: tejabhargavpodila@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SchoolManagementSystemApi);
  }
}(this, function(expect, SchoolManagementSystemApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AddConcessionRequest', function() {
      beforeEach(function() {
        instance = new SchoolManagementSystemApi.AddConcessionRequest();
      });

      it('should create an instance of AddConcessionRequest', function() {
        // TODO: update the code to test AddConcessionRequest
        expect(instance).to.be.a(SchoolManagementSystemApi.AddConcessionRequest);
      });

      it('should have the property applicationNumber (base name: "applicationNumber")', function() {
        // TODO: update the code to test the property applicationNumber
        expect(instance).to.have.property('applicationNumber');
        // expect(instance.applicationNumber).to.be(expectedValueLiteral);
      });

      it('should have the property studentName (base name: "studentName")', function() {
        // TODO: update the code to test the property studentName
        expect(instance).to.have.property('studentName');
        // expect(instance.studentName).to.be(expectedValueLiteral);
      });

      it('should have the property feeType (base name: "feeType")', function() {
        // TODO: update the code to test the property feeType
        expect(instance).to.have.property('feeType');
        // expect(instance.feeType).to.be(expectedValueLiteral);
      });

      it('should have the property amount (base name: "amount")', function() {
        // TODO: update the code to test the property amount
        expect(instance).to.have.property('amount');
        // expect(instance.amount).to.be(expectedValueLiteral);
      });

      it('should have the property reason (base name: "reason")', function() {
        // TODO: update the code to test the property reason
        expect(instance).to.have.property('reason');
        // expect(instance.reason).to.be(expectedValueLiteral);
      });

      it('should have the property issuedBy (base name: "issuedBy")', function() {
        // TODO: update the code to test the property issuedBy
        expect(instance).to.have.property('issuedBy');
        // expect(instance.issuedBy).to.be(expectedValueLiteral);
      });

      it('should have the property issuedDate (base name: "issuedDate")', function() {
        // TODO: update the code to test the property issuedDate
        expect(instance).to.have.property('issuedDate');
        // expect(instance.issuedDate).to.be(expectedValueLiteral);
      });

    });
  });

}));
