import React from 'react';
import Navbar from "./Navbar";
function DownloadReceipt({ receiptData }) {
    // Assume receiptData contains all the necessary information

    return (
        <div>
            <div className="receipt-container">
                
                <h1 className='text-4xl font-bold text-gray-500 mb-4'>NINE EDUCATION</h1>
                <div className="divider"></div> 
                <h1 className='text-3xl font-bold text-gray-500 mb-4'>FEE RECEIPT</h1>
                <div className="divider"></div> 
                <div className="receipt-header">
                <p>Receipt No: [Autogenerated Receipt Number]</p>
                <div className="divider"></div> 
                <p>Student Name: [Student's Name]</p>
                <p>Parent's Name: [Parent's Name]</p>
                <p>Application Number: [Application Number]</p>
                <p>Registered Mobile: [Mobile Number]</p>
                <p>Batch: [Batch]</p>
                <p>Stream: [Stream]</p>
                <p>Branch: [Branch]</p>
                </div>
                <div className="fee-details">
                <table>
                    <tr>
                    <th>Description</th>
                    <th>Amount</th>
                    </tr>
                    <tr>
                    <td>1st Year Tuition Fee</td>
                    <td>[Amount]</td>
                    </tr>
                    <tr>
                    <td>1st Year Hostel Fee</td>
                    <td>[Amount]</td>
                    </tr>
                </table>
                </div>
                <div className="total-amount">
                <p>Total Amount Paid: [Total Amount]</p>
                </div>
                <div className="student-details">
                <p>Date of Joining: [Date]</p>
                <p>Gender: [Gender]</p>
                <p>Residence Type: [Residence Type]</p>
                </div>
                <div className="transaction-details">
                </div>
                <div className="footer-note">
                <p>This is an auto-generated receipt and does not require a seal or signature.</p>
                <p>Contact Number: [Contact Number]</p>
                <p>Website: [Website URL]</p>
                </div>
            </div>
        </div>
        
  
    );
}

export default DownloadReceipt;

